In [42]:
import pandas as pd
import numpy as np

In [43]:
max_temp_air = 65*1.5
max_temp_water = 100*1.5
max_temp_oil = 115*1.5

min_temp = 0.0

In [44]:
df = pd.read_csv('ar41_for_ulb.csv', sep=";")
df = df.drop_duplicates()

In [45]:
df.head()

,Unnamed: 0,mapped_veh_id,timestamps_UTC,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2
0,0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,83.0,81.0,76.0,77.0
1,1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,78.0,78.0,73.0,74.0
2,2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,82.0,82.0,85.0,87.0
3,3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,77.0,81.0,78.0,82.0
4,4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,85.0,78.0,82.0,79.0

In [46]:
df.describe()

,Unnamed: 0,mapped_veh_id,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2
count,1.767927e+07,1.767927e+07,1.767927e+07,1.767927e+07,1.767927e+07,1.766655e+07,1.767927e+07,1.766655e+07,1.767927e+07,1.766655e+07,1.767927e+07,1.766655e+07,1.767927e+07,1.766655e+07
mean,8.839636e+06,1.508423e+02,5.087641e+01,4.228568e+00,3.202422e+01,3.233414e+01,2.636115e+02,2.706874e+02,9.122489e+02,9.079636e+02,7.693166e+01,7.614234e+01,7.654693e+01,7.616182e+01
std,5.103567e+06,2.694316e+01,3.133396e-01,5.981553e-01,3.280040e+02,3.479992e+02,1.152382e+02,1.161168e+02,3.833051e+02,3.884709e+02,1.365462e+01,1.452870e+01,1.450369e+01,1.535040e+01
min,0.000000e+00,1.020000e+02,4.829568e+01,1.750491e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.500000e+01,-1.700000e+01,-1.280000e+02,0.000000e+00
25%,4.419818e+06,1.280000e+02,5.077065e+01,3.715411e+00,2.200000e+01,2.200000e+01,2.030000e+02,2.100000e+02,7.970000e+02,7.970000e+02,7.700000e+01,7.600000e+01,7.400000e+01,7.400000e+01
50%,8.839636e+06,1.510000e+02,5.100253e+01,3.873272e+00,3.200000e+01,3.300000e+01,2.380000e+02,2.480000e+02,8.010000e+02,8.010000e+02,8.100000e+01,8.100000e+01,8.100000e+01,8.100000e+01
75%,1.325945e+07,1.740000e+02,5.108688e+01,4.535240e+00,4.000000e+01,3.900000e+01,3.200000e+02,3.310000e+02,8.120000e+02,8.110000e+02,8.400000e+01,8.400000e+01,8.500000e+01,8.500000e+01
max,1.767927e+07,1.970000e+02,5.285706e+01,8.045492e+00,6.553500e+04,6.553500e+04,6.900000e+02,6.900000e+02,2.309000e+03,9.732000e+03,1.090000e+02,1.190000e+02,1.270000e+02,1.170000e+02

In [47]:
df_dropped = df.dropna()

Drop when both motors are stopped

In [48]:
#df_motor_stopped = df_dropped[(df_dropped['RS_E_RPM_PC1'] == 0) & (df_dropped['RS_E_RPM_PC2'] == 0)]
#df_dropped.drop(df_motor_stopped.index)

In [49]:
df_motor_stopped = (df_dropped['RS_E_RPM_PC1'] == 0) & (df_dropped['RS_E_RPM_PC2'] == 0)
df_dropped = df_dropped[~df_motor_stopped]

In [ ]:
df_motor_stopped

0    False
1    False
2    False
3    False
4    False
dtype: bool

Maintenance center (found with google maps sattelite view)

In [51]:
df_maintenance1 = df[(df["lat"] <= 51.017182) & (df["lat"] >= 51.010652) & (df["lon"] >= 3.770148) & (df["lon"] <= 3.783246)]
df_maintenance2 = df[(df["lat"] <= 50.401860) & (df["lat"] >= 50.398082) & (df["lon"] >= 4.452937) & (df["lon"] <= 4.466798)]

Replacing values outside of the range by -1

In [53]:
columns = ['RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_WatTemp_PC1', 'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2']
limits = [max_temp_air, max_temp_air, max_temp_water, max_temp_water, max_temp_oil, max_temp_oil]

for col, max_temp in zip(columns, limits):
    df_dropped.loc[(df_dropped[col] < min_temp) | (df_dropped[col] > max_temp), col] = -1

In [ ]:
df_dropped.describe()

,Unnamed: 0,mapped_veh_id,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2
count,3.162230e+05,316223.000000,316223.000000,316223.000000,316223.00000,316223.000000,316223.000000,316223.000000,316223.0,316223.000000,316223.000000,316223.000000,316223.000000,316223.000000
mean,8.852314e+06,159.526249,50.937623,4.268786,33.29489,30.176765,30.994169,283.751505,0.0,935.072786,38.852469,75.970301,46.639457,74.805221
std,5.106694e+06,27.642290,0.261609,0.631019,20.47753,11.019492,88.972684,104.553579,0.0,343.527268,26.059985,14.514634,23.869673,17.438813
min,7.300000e+01,102.000000,48.295677,3.347395,-1.00000,-1.000000,0.000000,0.000000,0.0,8.200000,0.000000,-1.000000,-1.000000,0.000000
25%,4.440498e+06,139.000000,50.869239,3.771871,18.00000,22.000000,0.000000,217.000000,0.0,798.000000,19.000000,76.000000,27.000000,73.000000
50%,8.858056e+06,162.000000,51.013893,3.918941,33.00000,32.000000,3.000000,251.000000,0.0,801.000000,33.000000,80.000000,43.000000,80.000000
75%,1.325697e+07,189.000000,51.107492,4.852150,50.00000,38.500000,6.000000,341.000000,0.0,809.000000,62.000000,84.333333,71.000000,85.000000
max,1.767919e+07,197.000000,51.302863,8.045492,91.00000,82.000000,690.000000,690.000000,0.0,6790.500000,109.000000,105.000000,127.000000,117.000000

In [ ]:
df_dropped.to_csv('ar41_for_ulb_dropped.csv', sep=";", index=False)